# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2021-07-08T11:31:02+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Union

from pydantic import BaseModel
from pydantic import conint
from pydantic import constr
from pydantic import Field
from pydantic import UUID4


class InclusionStatus(Enum, str):
    STATUS_DEVICE_INCLUDING = 'STATUS_DEVICE_INCLUDING'
    STATUS_DEVICE_INCLUSION_SUCCESS = 'STATUS_DEVICE_INCLUSION_SUCCESS'
    STATUS_DEVICE_INCLUSION_FAILURE = 'STATUS_DEVICE_INCLUSION_FAILURE'
    STATUS_DEVICE_REPORTING = 'STATUS_DEVICE_REPORTING'
    STATUS_DEVICE_REPORT_SUCCESS = 'STATUS_DEVICE_REPORT_SUCCESS'
    STATUS_DEVICE_REPORT_FAILURE = 'STATUS_DEVICE_REPORT_FAILURE'
    EXCLUDED = 'EXCLUDED'
    INCLUDED = 'INCLUDED'


class FirmwareStatus(Enum, str):
    UP_TO_DATE = 'UP_TO_DATE'
    UPDATE_AVAILABLE = 'UPDATE_AVAILABLE'
    UPLOADING = 'UPLOADING'
    UPLOAD_COMPLETE = 'UPLOAD_COMPLETE'
    UPLOADING_FAILURE = 'UPLOADING_FAILURE'
    FLASHING = 'FLASHING'
    FLASHING_COMPLETE = 'FLASHING_COMPLETE'
    FLASHING_FAILURE = 'FLASHING_FAILURE'


class Command(Enum, str):
    idle = 'idle'
    firmware_upload = 'firmware_upload'
    firmware_flash = 'firmware_flash'
    firmware_cancel = 'firmware_cancel'
    include = 'include'
    exclude = 'exclude'
    connection_check = 'connection_check'


class OwnerEnum(Enum, str):
    unassigned = 'unassigned'


class Deletion(Enum, str):
    pending = 'pending'
    failed = 'failed'


class WappstoVersion(str, Enum):
    v2_0 = "2.0"
    v2_1 = "2.1"


class Permission(Enum, str):
    read = 'r'
    write = 'w'
    readwrite = 'rw'
    writeread = 'wr'
    none = 'none'


class EventStatus(Enum, str):
    ok = 'ok'
    update = 'update'
    pending = 'pending'


class StateType(Enum, str):
    report = 'Report'
    control = 'Control'


class StateStatus(Enum, str):
    send = 'Send'
    pending = 'Pending'
    failed = 'Failed'


class Level(Enum, str):
    important = 'important'
    error = 'error'
    warning = 'warning'
    info = 'info'
    debug = 'debug'


class StatusType(Enum, str):
    public_key = 'public key'
    memory_information = 'memory information'
    device_description = 'device description'
    value_description = 'value description'
    value = 'value'
    partner_information = 'partner information'
    action = 'action'
    calculation = 'calculation'
    timer = 'timer'
    calendar = 'calendar'
    statemachine = 'statemachine'
    firmware_update = 'firmware update'
    configuration = 'configuration'
    exi = 'exi'
    system = 'system'
    application = 'application'
    gateway = 'gateway'


class WappstoMetaType(str, Enum):
    """
    All possible Wappsto Meta Types.

    They have a parent child relation in order of:
    network->device->value->state

    Where a 'Network' only contains 'Device's,
    'Device's only contains 'value's, and
    'Value's only contains 'State's.
    """
    network = "network"
    device = "device"
    value = "value"
    state = "state"


class WarningItem(BaseModel):
    message: Optional[Optional[str]] = None
    data: Optional[Optional[Dict[str, Any]]] = None
    code: Optional[Optional[int]] = None


class Geo(BaseModel):
    latitude: Optional[str] = None
    longitude: Optional[str] = None
    display_name: Optional[str] = None
    address: Optional[Dict[str, Any]] = None


class BaseMeta(BaseModel):  # Base Meta
    id: Optional[UUID4] = None
    # #  type: Optional[WappstoMetaType] = None
    version: Optional[WappstoVersion] = None

    manufacturer: Optional[UUID4] = None
    owner: Optional[Union[UUID4, OwnerEnum]] = None
    parent: Optional[UUID4] = None

    created: Optional[datetime] = None
    updated: Optional[datetime] = None
    changed: Optional[datetime] = None

    application: Optional[UUID4] = None
    deletion: Optional[Deletion] = None
    deprecated: Optional[Optional[bool]] = None

    iot: Optional[Optional[bool]] = None
    revision: Optional[Optional[int]] = None
    size: Optional[Optional[int]] = None
    path: Optional[Optional[str]] = None

    oem: Optional[Optional[str]] = None
    accept_manufacturer_as_owner: Optional[Optional[bool]] = None
    redirect: Optional[
        constr(regex=r'^[0-9a-zA-Z_-]+$', min_length=1, max_length=200)
    ] = None
    
    error: Optional[UUID4] = None
    warning: Optional[List[WarningItem]] = None
    trace: Optional[Optional[str]] = None

    set: Optional[List[UUID4]] = None
    contract: Optional[List[UUID4]] = None


class StatusMeta(BaseMeta):
    class WappstoMetaType(str, Enum):
        status = "status"
    type: Optional[WappstoMetaType] = None


class ValueMeta(BaseMeta):
    class WappstoMetaType(str, Enum):
        value = "value"
    type: Optional[WappstoMetaType] = None

    historical: Optional[bool] = None 


class StateMeta(BaseMeta):
    class WappstoMetaType(str, Enum):
        state = "state"
    type: Optional[WappstoMetaType] = None

    historical: Optional[bool] = None 


class DeviceMeta(BaseMeta):
    class WappstoMetaType(str, Enum):
        device = "device"
    type: Optional[WappstoMetaType] = None

    geo: Optional[Geo] = None
    historical: Optional[bool] = None


class NetworkMeta(BaseMeta):
    class WappstoMetaType(str, Enum):
        network = "network"
    type: Optional[WappstoMetaType] = None

    geo: Optional[Geo] = None
    historical: Optional[bool] = None

    connection: Optional[Connection] = None
    accept_test_mode: Optional[bool] = None
    verify_product: Optional[str] = None
    product: Optional[str] = None


class Status(BaseModel):
    message: str
    timestamp: datetime
    data: Optional[str] = None
    level: Level
    type: StatusType
    meta: Optional[StatusMeta] = Field(None, title='meta-2.0:create')


class Info(BaseModel):
    enabled: Optional[bool] = None


class DeviceItem(BaseModel):
    name: Optional[str] = None
    control_timeout: Optional[int] = None
    control_when_offline: Optional[bool] = None
    manufacturer: Optional[str] = None
    product: Optional[str] = None
    version: Optional[str] = None
    serial: Optional[str] = None
    description: Optional[str] = None
    protocol: Optional[str] = None
    communication: Optional[str] = None
    included: Optional[str] = None
    inclusion_status: Optional[InclusionStatus] = None
    firmware_status: Optional[FirmwareStatus] = None
    firmware_upload_progress: Optional[str] = None
    firmware_available_version: Optional[str] = None
    command: Optional[Command] = None
    meta: Optional[DeviceMeta] = Field(None, title='meta-2.0:create')
    status: Optional[List[Union[Status, UUID4]]] = None
    value: Optional[
        List[
            Union[
                StringValue,
                NumberValue,
                BlobValue,
                XmlValue,
                UUID4
            ]
        ]
    ] = None
    info: Optional[Info] = None


class Connection(BaseModel):
    timestamp: Optional[datetime] = None
    online: Optional[bool] = None


class Network(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    device: Optional[List[Union[DeviceItem, UUID4]]] = None
    meta: Optional[NetworkMeta] = Field(None, title='meta-2.0:create')
    info: Optional[Info] = None


class StateItem(BaseModel):
    data: str
    type: StateType

    meta: Optional[StateMeta] = Field(None, title='meta-2.0:create')
    status: Optional[StateStatus] = None
    status_payment: Optional[str] = None
    timestamp: Optional[datetime] = None


class Number(BaseModel):
    min: float
    max: float
    step: float
    mapping: Optional[Dict[str, Any]] = None
    meaningful_zero: Optional[bool] = None
    ordered_mapping: Optional[bool] = None
    si_conversion: Optional[str] = None
    unit: Optional[str] = None


class String(BaseModel):
    max: Optional[conint(ge=1, multiple_of=1)] = None
    encoding: Optional[str] = None


class Blob(BaseModel):
    max: Optional[conint(ge=1, multiple_of=1)] = None
    encoding: Optional[str] = None


class Xml(BaseModel):
    xsd: Optional[str] = None
    namespace: Optional[str] = None


class BaseValue(BaseModel):
    name: Optional[str] = None
    type: Optional[str] = None

    description: Optional[str] = None
    period: Optional[str] = None
    delta: Optional[str] = None
    permission: Optional[Permission] = None
    status: Optional[EventStatus] = None
    meta: Optional[ValueMeta] = Field(None, title='meta-2.0:create')
    state: Optional[List[Union[StateItem, UUID4]]] = None
    info: Optional[Info] = None


class StringValue(BaseValue):
    string: Optional[String] = None


class NumberValue(BaseValue):
    number: Optional[Number] = None


class BlobValue(BaseValue):
    blob: Optional[Blob] = None


class XmlValue(BaseValue):
    xml: Optional[Xml] = None
