name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy

    - name: Analysing the code with flake8
      run: flake8 --docstring-convention google --ignore D212,W503 $(git ls-files 'wappstoiot/*.py')

    - name: Analysing the code with mypy
      run: mypy --strict --python-version 3.7  $(git ls-files 'wappstoiot/*.py')
